---
# Ansible playbook to run Windows Update and restart, if required
#
# http://docs.ansible.com/ansible/win_updates_module.html
# https://docs.ansible.com/ansible/win_reboot_module.html

- name:  Baseline Folders
  hosts: all
  gather_facts: false
  tasks:
    - name: Create Ansible log folder
      win_file:
        path: C:\Temp\AnsibleLogs
        state: directory
